export const GET_FORMS_DATA = "GET_FORMS_DATA";
export const GET_FORMS_ERROR = "GET_FORMS_ERROR";
export const GET_FORMS_FETCH_DATA = "GET_FORMS_FETCH_DATA";
export const GET_FORMS_CLEAR = "GET_FORMS_CLEAR";
export const POST_FORMS_DATA = "POST_FORMS_DATA";
export const POST_FORMS_ERROR = "POST_FORMS_ERROR";
export const POST_FORMS_FETCH_DATA = "POST_FORMS_FETCH_DATA";
export const POST_FORMS_CLEAR = "POST_FORMS_CLEAR";
